### ISSUE TITLE
Lunar Kick-Off Checklist

### ISSUE THREAD

**Issue by mikaelarguedas** [ros/rosdistro#13550]
This is a checklist of things to do for the Lunar kick-off (pre development and development):
- [x] Choose distribution name: Lunar
- [x] commission a logo
- [x] Add to REP3 with proposed platforms and minimum requirements, request feedback from community https://github.com/ros-infrastructure/rep/pull/123
- [x] List on ROS wiki with expected release date (http://wiki.ros.org/Distributions)
- [x] Add Ubuntu Z + Debian Stretch to bootstrap repository on repos.ros.org  https://github.com/ros-infrastructure/reprepro-updater/pull/35
- [x] Add Ubuntu Z + Debian Stretch to buildfarm_deployment_config https://github.com/ros-infrastructure/buildfarm_deployment_config/pull/17 (note that one is not the live one it's for reference only)
- [x] Add Ubuntu Z + Debian Stretch to ros_buildfarm/common.py https://github.com/ros-infrastructure/ros_buildfarm/pull/360

---
- [x] Add newly supported platforms to list of platforms for each Python package (in `stdeb.cfg`), in order of dependency (for ROS M, do this as soon as debs for new Ubuntu are available, in pre-alpha!):
  - [x] rospkg (uploaded, no need to rerelease): https://github.com/ros-infrastructure/rospkg/commit/60109b662b1cfd0e3fb8d59d1a72069cbbb631b9
  - [x] catkin_pkg (uploaded, no need to rerelease): https://github.com/ros-infrastructure/catkin_pkg/commit/0b418ae10260025016322e1f665c418bc726e241
  - [x] rosdistro (uploaded, no need to rerelease): https://github.com/ros-infrastructure/rosdistro/commit/1ba7c979d81a2d7358d608b15af233ffa4ec831f
  - [x] rosdep (uploaded, no need to rerelease):  https://github.com/ros-infrastructure/rosdep/commit/40067652cd0cde9d192e00788500d67124a30e27
  - [x] vcstools (uploaded, no need to rerelease): https://github.com/vcstools/vcstools/commit/a7b6e09e41145b5ade6251c9ae4562e8f0ae7935
  - [x] wstool (uploaded, no need to rerelease): https://github.com/vcstools/wstool/commit/84f0fe6497c88f7a95ab688aa2e39eb731d54e7b
  - [x] rosinstall (uploaded, no need to rerelease): https://github.com/vcstools/rosinstall/commit/5e12046c021b96d8e71f6c86ea427ec362fe6d1d
  - [x] bloom (uploaded, no need to rerelease):  https://github.com/ros-infrastructure/bloom/commit/9e35e0f53bad69e62f2e4df66d7830138d7ba5bb
  - [x] rosinstall_generator (uploaded, no need to rerelease):  https://github.com/ros-infrastructure/rosinstall_generator/commit/c89c9764e2fddd0d5f1f552f10282e6a9c43e591
  - [x] catkin_tools (uploaded, no need to rerelease): https://github.com/catkin/catkin_tools/commit/e5bb5d842dca57e489df5f06ec5fa71c3527324a
  - [x] vcstool: https://github.com/dirk-thomas/vcstool/commit/25a7c5461351906ea8de0522381b95321628da2d and https://github.com/dirk-thomas/vcstool/commit/953b294b4d379642168f1ba08a1f98b6322b8a2b
- [x] Use [`ros_release_python`](https://github.com/ros-infrastructure/ros_release_python) to make the currently released versions available in the new distros. Use the `--include` option
~~- [ ] Import third-party packages for the newly targeted platforms~~ Moved to Release checklist and ask maintainer to request the import of packages they need

---
- [x] create Docker images for the new platforms for all targets https://github.com/osrf/multiarch-docker-image-generation/pull/1

---
- [x] Create distribution files in ros/rosdistro https://github.com/ros/rosdistro/pull/13676
- [x] add [ros_buildfarm_config](https://github.com/ros-infrastructure/ros_buildfarm_config) lunar entries https://github.com/ros-infrastructure/ros_buildfarm_config/pull/69
  - [x] create new mailing list (https://groups.google.com/forum/#!forum/ros-buildfarm-lunar) with exactly the same settings as the existing ones
- [x] generate new management jobs (see https://github.com/ros-infrastructure/ros_buildfarm/blob/master/doc/deploy_configuration.rst)

---
- [x] [prerelease website](https://github.com/ros-infrastructure/prerelease_website)
  - [x] Add new column in for the new distro with theme and placeholder image https://github.com/ros-infrastructure/prerelease_website/pull/34 and https://github.com/ros-infrastructure/prerelease_website/pull/36
  - [x] Add new LTS distros as preferred: ros-infrastructure/prerelease_website#35
  - [x] Make xenial the preferred guest ros-infrastructure/prerelease_website#37
  - [x] Test prerelease process (except for [latest ubuntu distros](https://github.com/ros-infrastructure/ros_buildfarm/issues/394))

---
- [x] Add Lunar button to the [wiki](https://github.com/ros-infrastructure/roswiki)
~~- [ ] Add distribution to ROS browse tabs~~ This should be on the Release checklist ( based on https://github.com/ros/rosdistro/issues/13550#issuecomment-284591246)
~~- [ ] Edit wiki pages to contain proper content for the Lunar tag. tracked by https://github.com/ros/rosdistro/issues/13677~~ All these use the `and_newer` macros and thus will have proper content for lunar once generated
- [x] Add standard distribution wiki pages (planning, migration, etc...)
  - [x] http://wiki.ros.org/lunar
  - [x] http://wiki.ros.org/lunar/Planning
  - [x] http://wiki.ros.org/lunar/Migration
    - [x] `ros_comm` http://wiki.ros.org/action/diff/lunar/Migration?action=diff&rev1=1&rev2=2
  - [x] http://wiki.ros.org/lunar/Planning/Maintenance
    - [x] link to the blocked releases status page rather than using a static page
    - [x] update previous distributions Maintenance pages accordingly
  - [x] http://wiki.ros.org/lunar/Installation
    - [x] Pages created  http://wiki.ros.org/lunar/Installation
    - [x] Fill out [Ubuntu](http://wiki.ros.org/lunar/Installation/Ubuntu) and [Debian](http://wiki.ros.org/lunar/Installation/Debian) Installation pages

---
*tag people once buildfarm is ready*
- [x] Release `ros-base` packages into Lunar
  - [x] catkin (@dirk-thomas) https://github.com/ros-gbp/catkin-release/commit/a62289f1c4160a93ebe0e5da3bf900f3cb5e2e02
  - [x] genmsg (@dirk-thomas)
  - [x] gencpp (@dirk-thomas)
  - [x] geneus (@k-okada)
  - [x] genlisp (@dirk-thomas)
  - [x] genpy (@dirk-thomas)
  - [x] gennodejs (@chris-smith @IanTheEngineer)
  - [x] roscpp_core (@dirk-thomas)
  - [x] message_generation (@dirk-thomas)
  - [x] message_runtime (@dirk-thomas)
  - [x] rosbag_migration_rule (@dirk-thomas)
  - [x] std_msgs (@dirk-thomas)
  - [x] ros_comm_msgs (@dirk-thomas)
  - [x] cmake_modules (@wjwwood)
  - [x] rospack (@dirk-thomas)
  - [x] ros (@dirk-thomas)
  - [x] roslisp (@dirk-thomas)
  - [x] ros_comm (@dirk-thomas)
  - [x] rosconsole_bridge (@dirk-thomas)
  - [x] common_msgs (tfoote)
  - [x] ros_tutorials (@dirk-thomas)
    - [x] needs to be re-released as soon as the Lunar turtle is available
  - [x] actionlib (mikaelarguedas)
  - [x] angles (@tfoote)
  - [x] bond_core (mikaelarguedas)
  - [x] dynamic_reconfigure (mikaelarguedas)
  - [x] class_loader (@mikaelarguedas)
  - [x] pluginlib (mikaelarguedas)
  - [x] nodelet_core (mikaelarguedas)
  - [x] common_tutorials (wjwwood & stonier)

---
- [x] Create lunar category on Discourse https://discourse.ros.org/c/release/lunar
- [x] Announce availability of the Lunar build farm
- [x] Update mirror documentation (see https://github.com/ros-infrastructure/mirror/commits/master for examples) 
  - [x] update ros mirrors https://github.com/ros-infrastructure/mirror/pull/6
  - [x] update osrfoundation mirrors (wait until there are builds for ignition and gazebo for all supported platforms)
- [x] Announce logo design and kick off t-shirt campaign

**Comment by dirk-thomas** [comment]
@k-okada Can you please release `geneus` into Lunar.

@chris-smith Can you please release `gennodejs` into Lunar.

It can be just the latest Kinetic release so that we can continue releasing the ROS core packages quickly. Thanks!

**Comment by chris-smith** [comment]
Done! ( through @IanTheEngineer )

**Comment by dirk-thomas** [comment]
@chris-smith @IanTheEngineer Thank you guys for the super quick action :rocket:

**Comment by dirk-thomas** [comment]
@wjwwood Can you please release `cmake_modules` into Lunar including changes specific to Lunar (e.g. ros/cmake_modules#42).

**Comment by wjwwood** [comment]
Sure, here's the release pr: https://github.com/ros/rosdistro/pull/13957

**Comment by dirk-thomas** [comment]
@wjwwood Thanks for the fast release.

**Comment by k-okada** [comment]
`geneus` done -> https://github.com/ros/rosdistro/pull/13962

**Comment by dirk-thomas** [comment]
@k-okada Thank you for the quick release :rocket:

**Comment by mikaelarguedas** [comment]
@tfoote you should be able to release `common_msgs` now that `std_msgs` and below have been released

**Comment by mikaelarguedas** [comment]
thanks @tfoote for the quick release!

**Comment by mikaelarguedas** [comment]
@stonier  Can you please release `common_tutorials` into Lunar?

It can be just the latest Kinetic release. It's just to make sure that it actually builds properly.
Thanks!

**Comment by dirk-thomas** [comment]
Actually it won't build atm because of some parent sourcedeb jobs being stuck. Therefore it's also not possible to test it using Debian packages of the dependencies.

**Comment by stonier** [comment]
Aye, not going to build, but at least all the dependencies are there so it can be bloomed -> [ros/rosdistro#13999](https://github.com/ros/rosdistro/pull/13999).

When the deps are built, it should be right to go.

**Comment by dirk-thomas** [comment]
I added a new bullet to the second block in the first comment: third-party packages need to be imported into the repo for all newly targeted platforms. One example I ran into which is currently missing: ros-infrastructure/ros_bootstrap_dependencies#5

Looking at http://repositories.ros.org/status_page/lunar_default.html other packages seem to be missing as well.

**Comment by mikaelarguedas** [comment]
@dirk-thomas We decided to remove this bullet from this checklist and ask maintainers to request import of third party packages as they release. That allows us to flush out the packages that shouldn't be imported in the first place and to treat imports one at a time. So I'm going to remove this bullet and make it explicit on the release checklist ticket.

Thanks for pointing it out

**Comment by mikaelarguedas** [comment]
@ros/ros_team I'm not sure what the purpose of the [Maintenance page](http://wiki.ros.org/kinetic/Planning/Maintenance) is, so could use some input on the following proposal.

I am considering redirecting the `Maintenance page` to the [status_page](http://repositories.ros.org/status_page/blocked_releases_lunar.html?q=id%3D%22metapackages%22&s=6&r=1) created for this purpose.

Pros:
- Up to date because generated periodically by the buildfarm
- Avoid having to generate manually the page every so often

Cons:
- It's not as eye friendly as the previous one and displays only the "Not released" packages

Alternative:
- generate a Maintenance page periodically during the beta cycle so that it stays roughly up to date
- leave it as is once all is green

Feedback welcome :)

**Comment by dirk-thomas** [comment]
I think the new status page should replace the former wiki page.

**Comment by tfoote** [comment]
+1 for replacing with the automated page. This wiki page was our manual approach to automating it. 

I'd suggest replacing the contents with a little bit of tutorials on how to use the status pages effectively. (aka a few sentances explaining the search queries and terms.)

**Comment by wjwwood** [comment]
Yup, +1 for replacing it.

**Comment by mikaelarguedas** [comment]
sounds good, thanks all for the quick feedback, I'll do that then.

**Comment by mikaelarguedas** [comment]
@wjwwood can you confirm that "Add distribution to ROS browse tabs" was done in https://github.com/ros-infrastructure/rosbrowse/pull/4 ?

Should this be a single item on the [release checklist](https://github.com/ros/rosdistro/issues/14112) that consists in : 
 - adding the name of the next rosdistro (once ROS-M name has been decided)
 - updating the active one
and be completely removed from the Kickoff checklist?

**Comment by wjwwood** [comment]
That's the right pr to update rosbrowse. I agree it should be part of the release and not the kick-off checklist because we usually announce the next name at the release of the current one and we shouldn't update lunar to be the default until it is released.

**Comment by mikaelarguedas** [comment]
ok thanks for confirming, removing it from this checklist then

**Comment by wjwwood** [comment]
🎉
