### ISSUE TITLE
Lunar Release Checklist

### ISSUE THREAD

**Issue by mikaelarguedas** [ros/rosdistro#14112]
This ticket is used to collect things that need to be done for the upcoming Lunar release. (copied from the [Kinetic Release ticket](https://github.com/ros/rosdistro/issues/9944))

Existing Task Sets:
- [x] Lunar kickoff list https://github.com/ros/rosdistro/issues/13550
- [x] Lunar documentation audit
- [ ] Lunar community documentation audit

---
Documentation:
- [x] Update verbiage on these wiki pages, e.g. 'upcoming release' vs. 'current release'
  - [x] http://wiki.ros.org/lunar/Installation
  - [x] http://wiki.ros.org/lunar
- [x] Turtlesim icon
- [x] M-turtle name

---
ROS Wiki
- [x] make distroN the default distro
- [x] Version macro for distroN needs to be updated from “Expected in distroN” to “distroN”
- [x] Manually redeploy wiki once finished by pulling repo and restarting Apache instance
- [x] Update symlink for default API doc:
  - /home/rosbot/docs/api → /home/rosbot/docs/distroN/api
  - /home/rosbot/latest → /home/rosbot/docs/distroN
- [x] Update http://wiki.ros.org/Distributions
  - reflect released status (update from pending)
- [x] Update http://wiki.ros.org/ROS/Installation to point to distroN
~~- [ ] remove EOL'd from header doc links~~ (will happen later see https://github.com/ros-infrastructure/roswiki/pull/204)

---
ROS browse
- [x] update default distro (https://github.com/ros-infrastructure/rosbrowse/pull/7)

---
ROS docker images
- [x] add Dockerfiles to create ROS docker images https://github.com/osrf/docker_images/pull/51
---
Communication
- [x] Announcement email to ros-users pointing to migration guide 
  - Post to ros-users
  - Post to blog
  - Post to G+
  - Post to Twitter

---
www.ros.org
- [x] Update www.ros.org bottom row widget to point to new release with logo
- [x] Update www.ros.org/install to point to new release with logo

**Comment by dirk-thomas** [comment]
@mikaelarguedas The table in [section 5](http://wiki.ros.org/Distributions#Which_distribution_to_use) needs an update too.

**Comment by mikaelarguedas** [comment]
I didn't update it because I thought we did not officially encourage people to switch until more packages (like navigation and moveit) were released. I'm happy to update it if it's not the case

**Comment by mikaelarguedas** [comment]
Lunar Loggerhead has been released :tada: and the community documentation will be improved along packages being released. Closing this
