### ISSUE TITLE
split rqt plugins into separate repos

### ISSUE THREAD

**Issue by dirk-thomas** [ros/rosdistro#14652]
This ticket is for tracking the progress for Lunar.

* [x] `rqt_common_plugins` ~~removed plugins ros-visualization/rqt_common_plugins#451, waiting for other packages~~

  * [x] `rqt_action` ~~waiting for maintainer ros-visualization/rqt_action#1~~
  * [x] `rqt_bag`
  * [x] `rqt_console`
  * [x] `rqt_dep`
  * [x] `rqt_graph`
  * [x] `rqt_image_view`
  * [x] `rqt_launch` ~~waiting for maintainer ros-visualization/rqt_launch#16~~
  * [x] `rqt_logger_level`
  * [x] `rqt_msg`
  * [x] `rqt_plot`
  * [x] `rqt_publisher`
  * [x] `rqt_py_console` ~~waiting for maintainer ros-visualization/rqt_py_console#1~~
  * [x] `rqt_reconfigure` ~~waiting for maintainer ros-visualization/rqt_reconfigure#6~~
  * [x] `rqt_service_caller`
  * [x] `rqt_shell` ~~waiting for maintainer ros-visualization/rqt_shell#3~~
  * [x] `rqt_srv`
  * [x] `rqt_top` ~~waiting for maintainerros-visualization/rqt_top#1~~
  * [x] `rqt_topic`
  * [x] `rqt_web`

* [x] `rqt_robot_plugins` ~~removed plugins ros-visualization/rqt_robot_plugins#123, waiting for other packages~~

  * [x] `rqt_moveit` ~~waiting for maintainer ros-visualization/rqt_moveit#3~~
  * [x] `rqt_nav_view` ~~waiting for maintainer ros-visualization/rqt_nav_view#1~~
  * [x] `rqt_pose_view`
  * [x] `rqt_robot_dashboard` ~~waiting for maintainer ros-visualization/rqt_robot_dashboard#1~~
  * [x] `rqt_robot_monitor` ~~waiting for maintainer ros-visualization/rqt_robot_monitor#4~~
  * [x] `rqt_robot_steering`
  * [x] `rqt_runtime_monitor` ~~waiting for maintainer ros-visualization/rqt_runtime_monitor#1~~
  * [x] `rqt_rviz` ~~waiting for maintainer ros-visualization/rqt_rviz#2~~
  * [x] `rqt_tf_tree` ~~waiting for maintainer ros-visualization/rqt_tf_tree#1~~

**Comment by dirk-thomas** [comment]
Lunar done - three more to go:

* [ ] Indigo
* [ ] Jade
* [ ] Kinetic
