### ISSUE TITLE
Melodic Release Checklist

### ISSUE THREAD

**Issue by clalancette** [ros/rosdistro#16139]
This ticket is used to collect things that need to be done for the upcoming Melodic release (copied from the [Lunar Release ticket](https://github.com/ros/rosdistro/issues/14112)).

- [x] Do a final sync of packages on the buildfarm (run the `rel_sync_packages_to_main` job, e.g. http://build.ros.org/job/Mrel_sync-packages-to-main/)

---
Existing Task Sets:
- [x] Melodic kickoff list https://github.com/ros/rosdistro/issues/16138
- [x] Melodic documentation audit
- [x] Melodic community documentation audit

---
Documentation:
- [x] Update verbiage on these wiki pages, e.g. 'upcoming release' vs. 'current release'
  - [x] http://wiki.ros.org/melodic/Installation
  - [x] http://wiki.ros.org/melodic
- [x] Turtlesim icon
- [x] N-turtle name

---
ROS Wiki
(all changes need to be made to https://github.com/ros-infrastructure/roswiki, PR'ed, merged, then pulled down on the wiki machine)
- [x] make distroX the default distro (https://github.com/ros-infrastructure/roswiki/pull/249)
- [x] Version macro for distroX needs to be updated from “Expected in distroX” to “distroX”
- [x] Manually redeploy wiki once finished by pulling repo and restarting Apache instance (roswiki checkout lives in `/var/www/wiki.ros.org/data/plugin`, restart apache with script in `/home/ros/reload_httpd`)
- [x] Update symlink for default API doc:
  - [x] /home/rosbot/docs/api → /home/rosbot/docs/distroX/api
  - [x] /home/rosbot/docs/latest → /home/rosbot/docs/distroX
  - [x] (if this is an LTS) /home/rosbot/docs/latest-lts -> /home/rosbot/docs/distroX
- [x] Update http://wiki.ros.org/Distributions
  - reflect released status (update from pending)
- [x] Update http://wiki.ros.org/ROS/Installation to point to distroX

---
ROS browse (https://github.com/ros-infrastructure/rosbrowse)
- [x] update default distro (https://github.com/ros-infrastructure/rosbrowse/pull/8)

---
ROS docker images
- [x] add Dockerfiles to create ROS docker images
---
Communication
- [x] Announcement email to ros-users pointing to migration guide 
  - Post to ros-users
  - Post to blog
  - Post to G+
  - Post to Twitter

---
www.ros.org
- [x] Update www.ros.org bottom row widget to point to new release with logo
- [x] Update www.ros.org/install to point to new release with logo

**Comment by clalancette** [comment]
Release is out!  Closing this.

**Comment by dhood** [comment]
FYI we missed a step of adding melodic to http://wiki.ros.org/Installation/Ubuntu and other high-level pages  e.g. http://wiki.ros.org/action/info/Installation/Ubuntu?action=diff&rev2=6&rev1=5
Should all be done now; mentioning here so it is not forgotten the next release.

**Comment by clalancette** [comment]
@dhood Thanks for the heads up.

**Comment by mikaelarguedas** [comment]
Note: It's likely because of the load of moinmoin but this page now shows me C-Turlte install instructions and takes more than 10 sec to display only the content for melodic

**Comment by tfoote** [comment]
Yeah, we're still transferring all of the content and it's only suppressed by the javascript that might be loading slowly for you remotely.
