### ISSUE TITLE
Melodic Python3 support tracking issue

### ISSUE THREAD

**Issue by clalancette** [ros/rosdistro#17898]
This is an issue to track some PRs that will make Python3 easier to use in Melodic.

* [x] https://github.com/ros/ros_environment/pull/4
  * [x] Release into Melodic
* [x] https://github.com/ros-infrastructure/rosdep/pull/607
* [ ] ~~https://github.com/ros-infrastructure/rep/pull/149~~ https://github.com/ros-infrastructure/rep/pull/201
* [x] https://github.com/ros-infrastructure/rep/pull/172
* [x] https://github.com/ros/catkin/pull/939
  * [x] Release into Melodic
* [x] Put some documentation somewhere on how to switch to Python3
  * http://wiki.ros.org/UsingPython3/

**Comment by sloretz** [comment]
I'll close this since the only thing remaining is ros-infrastructure/rep#201
