### ISSUE TITLE
Noetic Kick-off and Release Checklist

### ISSUE THREAD

**Issue by sloretz** [ros/rosdistro#21513]
This ticket is for things that need to be done for the May 2020 ROS 1 Noetic release. Copied from the [Melodic Release ticket](https://github.com/ros/rosdistro/issues/16139) and [Melodic Kick-Off Checklist](https://github.com/ros/rosdistro/issues/16138).

Prerequisites
---
- [x] Python 3 support for Melodic checklist (ros/rosdistro#17898)
- [x] Resolve how to do rosdep keys for python 3
  * some discussion [here](https://github.com/ros-infrastructure/rosdep/pull/607#issuecomment390354561)
- [x] Update and release [rep-151](https://github.com/ros-infrastructure/rep/pull/149) with python3 plan (ros-infrastructure/rep#201)

Kickoff part 1
---

- [x] Choose distribution name: **Noetic Ninjemys**
- [x] Commission a logo
- [x] Commission a turtlesim icon
- [x] Add to REP3 with proposed platforms and minimum requirements, request feedback from community (ros-infrastructure/rep#202)
- [x] List on ROS wiki with expected release date
  * http://wiki.ros.org/Distributions
  * see [example](http://wiki.ros.org/action/diff/Distributions?action=diff&rev1=80&rev2=81)
  * http://wiki.ros.org/action/info/Distributions?action=diff&rev2=102&rev1=99
  * Wiki page for noetic: http://wiki.ros.org/noetic

Ubuntu buildfarm setup
---
- [x] Create [`ros-buildfarm-noetic@googlegroups.com`](https://groups.google.com/forum/#!forum/ros-buildfarm-noetic)
- [x] Add Ubuntu 20.04 to bootstrap repository on repos.ros.org
  * see [example](https://github.com/ros-infrastructure/reprepro-updater/pull/51)
  * actual: https://github.com/ros-infrastructure/reprepro-updater/pull/72
- [x] Add Ubuntu 20.04  to buildfarm_deployment_config
  * note this is not the live one, it's for reference only
  * see [example](https://github.com/ros-infrastructure/buildfarm_deployment_config/pull/22)
  * actual: https://github.com/ros-infrastructure/buildfarm_deployment_config/pull/52
- [x] Add Ubuntu 20.04 to `ros_buildfarm/common.py`
  * see [example](https://github.com/ros-infrastructure/ros_buildfarm/pull/493)
  * actual: https://github.com/ros-infrastructure/ros_buildfarm/pull/699

Python Dependencies setup
---
- [ ] Check that all python packages and scripts below work with python 3.7 and 3.8
  - [ ] [catkin_pkg](https://github.com/ros-infrastructure/catkin_pkg)
  - [ ] [rospkg](https://github.com/ros-infrastructure/rospkg)
  - [ ] [rosdistro](https://github.com/ros-infrastructure/rosdistro)
  - [ ] [rosdep](https://github.com/ros-infrastructure/rosdep)
    * Py 3.7 + 3.8 CI https://github.com/ros-infrastructure/rosdep/pull/735
  - [ ] [vcstools](https://github.com/vcstools/vcstools)
  - [ ] [wstool](https://github.com/vcstools/wstool)
  - [ ] [rosinstall](https://github.com/vcstools/rosinstall)
  - [ ] [bloom](https://github.com/ros-infrastructure/bloom)
  - [ ] [rosinstall_generator](https://github.com/ros-infrastructure/rosinstall_generator)
  - [ ] [osrf_pycommon](https://github.com/osrf/osrf_pycommon)
  - [ ] [catkin_tools](https://github.com/catkin/catkin_tools)
  - [ ] [vcstool](https://github.com/dirk-thomas/vcstool)
  - [ ] [ros_release_python](https://github.com/ros-infrastructure/ros_release_python)
- [x] Add newly supported platforms to list of platforms for each Python package (in `stdeb.cfg`), in order of dependency
  * do this as soon as debs for new Ubuntu are available, in pre-alpha!
  - [x] catkin_pkg
    * Example (Melodic: ros-infrastructure/catkin_pkg#198)
    * Actual: ros-infrastructure/catkin_pkg#271
  - [x] rospkg
    * Example (Melodic: ros-infrastructure/rospkg#123)
    * Actual: ros-infrastructure/rospkg#184
  - [x] rosdistro
    * Example (Melodic: ros-infrastructure/rosdistro#108)
    * Actual: ros-infrastructure/rosdistro#148
  - [x] rosdep
    * Example (Melodic: ros-infrastructure/rosdep#567)
    * Actual: ros-infrastructure/rosdep#734
  - [ ] vcstools
    * Example (Melodic: vcstools/vcstools#127)
    * Actual: https://github.com/vcstools/vcstools/pull/159
  - [ ] wstool
    * Example (Melodic: vcstools/wstool#115)
    * Actual: vcstools/wstool#148
  - [ ] rosinstall
    * Example (Melodic: vcstools/rosinstall#113)
    * Actual: vcstools/rosinstall#122
  - [x] bloom
    * Example (Melodic: ros-infrastructure/bloom#452)
    * Actual: ros-infrastructure/bloom#558
  - [x] rosinstall_generator
    * Example (Melodic: ros-infrastructure/rosinstall_generator#42)
    * Actual: ros-infrastructure/rosinstall_generator#62
  - [x] osrf_pycommon
    * Example (Melodic: osrf/osrf_pycommon#45)
    * Actual: osrf/osrf_pycommon#58
  - [x] catkin_tools
    * Example (Melodic: catkin/catkin_tools#497)
    * Actual: ~~catkin/catkin_tools#589~~, catkin/catkin_tools#564
  - [x] vcstool
    * Example(Melodic: dirk-thomas/vcstool@dcee1a0)
    * Actual: dirk-thomas/vcstool#112
- [x] Use [`ros_release_python`](https://github.com/ros-infrastructure/ros_release_python)
    * Goal is to make the currently released versions available in the new distros using the `--include` option

---
- [x] create Docker images for the new platforms in rep 3 for all targets
  * See [example](https://github.com/osrf/multiarch-docker-image-generation/pull/10)
  * actual: https://github.com/osrf/multiarch-docker-image-generation/pull/32

---
- [x] Create distribution files in ros/rosdistro
  * [Example](https://github.com/ros/rosdistro/pull/16687)
  * Actual: https://github.com/ros/rosdistro/pull/21988
- [x] create new mailing list for buildfarm emails
  * [Example](https://groups.google.com/forum/#!forum/ros-buildfarm-melodic)
  * Use same settings as the existing ones (need to get admin on an older group to see settings)
  * Actual: https://groups.google.com/forum/#!forum/ros-buildfarm-noetic
- [x] Add ros_buildfarm_config entries
  * [Example](https://github.com/ros-infrastructure/ros_buildfarm_config/pull/102)
  * Actual: https://github.com/ros-infrastructure/ros_buildfarm_config/pull/157
- [x] [Generate new management jobs](https://github.com/ros-infrastructure/ros_buildfarm/blob/master/doc/deploy_configuration.rst)
- [x] generate new `sync-packages-to-{testing,main}` jobs
  * Run [this script](https://github.com/ros-infrastructure/ros_buildfarm/blob/master/scripts/release/generate_release_trigger_upload_jobs.py)

[Prerelease Website](https://github.com/ros-infrastructure/prerelease_website)
---
- [x] Release the `catkin`
  * Needed for prerelease website testing
  * [Example](https://github.com/ros-gbp/catkin-release/commit/a62289f)
  * Actual: https://github.com/ros/rosdistro/pull/23421
- [x] Add new column in for the new distro with theme and placeholder image
  * [Example](https://github.com/ros-infrastructure/prerelease_website/pull/47)
  * actual: https://github.com/ros-infrastructure/prerelease_website/pull/59 https://github.com/ros-infrastructure/prerelease_website/pull/60
- [ ] Make Ubuntu 20.04 the preferred OS
  * [Example](https://github.com/ros-infrastructure/prerelease_website/pull/52)
- [x] Test prerelease process (except for [latest ubuntu distros](https://github.com/ros-infrastructure/ros_buildfarm/issues/394))

Pre-release documentation
---
- [x] Add Noetic button to the [wiki](https://github.com/ros-infrastructure/roswiki) https://github.com/ros-infrastructure/roswiki/pull/298
- [x] Add standard distribution wiki pages (planning, migration, etc...)
  - [x] http://wiki.ros.org/noetic/
  - ~~http://wiki.ros.org/melodic/Planning~~ Appears unused in melodic, did not create Noetic equivalent
  - [x] http://wiki.ros.org/noetic/Migration
  - [x] http://wiki.ros.org/melodic/Planning/Maintenance
    - [x] link to the blocked releases status page rather than using a static page
    - ~~update previous distributions Maintenance pages accordingly~~
  - [x] http://wiki.ros.org/noetic/Installation
    - [x] Create main page http://wiki.ros.org/noetic/Installation
    - [x] Create [Platforms](http://wiki.ros.org/noetic/Installation/Platforms)
    - [x] Create [DebianSources](http://wiki.ros.org/noetic/Installation/DebianSources)
    - [x] Create [DebEnvironment](http://wiki.ros.org/noetic/Installation/DebEnvironment)
    - [x] Create [PostInstall](http://wiki.ros.org/noetic/Installation/PostInstall)
    * All of the below should have a warning about distribution pending [like this](http://wiki.ros.org/action/diff/lunar/Installation/Ubuntu?action=diff&rev1=1&rev2=2)
    - [x] Create [Ubuntu](http://wiki.ros.org/noetic/Installation/Ubuntu)
    - [x] Create [Debian](http://wiki.ros.org/noetic/Installation/Debian)
    - [x] Create [Source](http://wiki.ros.org/noetic/Installation/Source)

Low level releases
---
- [x] Release `ros-core` packages
  - [x] ros_environment
  - [x] rosbag_migration_rule
  - [x] roscpp_core
  - [x] genmsg
  - [x] gencpp
  - [x] geneus
  - [x] genlisp
  - [x] gennodejs
  - [x] genpy
  - [x] message_generation
  - [x] message_runtime
  - [x] ros_comm_msgs
  - [x] std_msgs
  - [x] cmake_modules
  - [x] rospack
  - [x] ros
  - [x] ros_comm
  - [x] rosconsole_bridge
  - [x] common_msgs
  - [x] ros_tutorials
    - [x] re-release as soon as the turtle is available (https://github.com/ros/ros_tutorials/pull/85)
  - [x] roslisp
- [x] Release `ros-base` packages
  - [x] actionlib
  - [x] angles
  - [x] bond_core
  - [x] dynamic_reconfigure
  - [x] class_loader
  - [x] pluginlib
  - [x] nodelet_core
- [x] common_tutorials

Early Buildfarm
---
- [x] Create [Migration page](http://wiki.ros.org/melodic/Migration)
  * http://wiki.ros.org/noetic/Migration
- [ ] Announce availability of the build farm
  * [Example](https://discourse.ros.org/t/melodic-morenia-buildfarm-available/4248)
- [x] Ping all maintainers of packages in `desktop-full`

Day prior and day of Release
---

- [x] Announce logo design and kick off t-shirt campaign*

**ROS Wiki**
- [x] make this the default distro
  * [example](https://github.com/ros-infrastructure/roswiki/pull/249)
  * actual: https://github.com/ros-infrastructure/roswiki/pull/302
- [x] Update Version macro from “Expected in distroX” to “distroX”
- [x] Manually redeploy wiki once finished by pulling repo and restarting Apache instance
  * roswiki checkout lives in `/var/www/wiki.ros.org/data/plugin`
  * restart apache with script in `/home/ros/reload_httpd`
- [ ] Update symlink for default API doc:
  - [ ] /home/rosbot/docs/api → /home/rosbot/docs/distroX/api
  - [ ] /home/rosbot/docs/latest → /home/rosbot/docs/distroX
  - [ ] (if this is an LTS) /home/rosbot/docs/latest-lts -> /home/rosbot/docs/distroX
- [x] Update http://wiki.ros.org/ROS/Installation to point to distroX
- [x] Update verbiage on these wiki pages, e.g. 'upcoming release' vs. 'current release'
  - [x] http://wiki.ros.org/noetic/Installation
  - [x] http://wiki.ros.org/noetic
  - [x] http://wiki.ros.org/Distributions

**[ROS browse](https://github.com/ros-infrastructure/rosbrowse)**
- [x] update default distro
  * [Example](https://github.com/ros-infrastructure/rosbrowse/pull/8)
  * actual: https://github.com/ros-infrastructure/rosbrowse/pull/9

**ROS docker images**
- [ ] add Dockerfiles to create ROS docker images

**Misc Infra**
- [ ] Update www.ros.org bottom row widget to point to new release with logo
- [ ] Update www.ros.org/install to point to new release with logo
- [x] Create Release category on Discourse
  * [Example](https://discourse.ros.org/c/release/melodic)
  * actual: https://discourse.ros.org/c/release/noetic/66
- [x] Update mirror documentation
  * [Example](https://github.com/ros-infrastructure/mirror/commits/master) 
- [x] update ros mirrors
  * [Example](https://github.com/ros-infrastructure/mirror/pull/14)
- [x] update osrfoundation mirrors
  * Must wait until there are builds for ignition and gazebo for all supported platforms
- [x] Add Noetic to high level page http://wiki.ros.org/Installation/Ubuntu
- [x] Add Noetic to index.ros.org (https://github.com/ros-infrastructure/rosindex/pull/231)

**Communication**
- [x] Announcement pointing to migration guide 
  - [x] Post to discourse
  - Post to blog
  - Post to G+
  - Post to Twitter

**Comment by nuclearsandwich** [comment]
>     * Goal is to make the currently released versions available in the new distros using the `--include` option

The --include option wasn't updated to support the new aptly-based bootstrap repository. I've opened https://github.com/ros-infrastructure/ros_release_python/issues/31 to track support for it and am hoping to tackle it well before it's needed.

**Comment by SteveMacenski** [comment]
It looks like `python-catkin-pkg` in Focal is missing from the python file, which blocks `geographic_info`. I can force release it but I feel like that should probably be fixed beforehand.

Thoughts?

**Comment by sloretz** [comment]
> It looks like `python-catkin-pkg` in Focal is missing from the python file, which blocks `geographic_info`. I can force release it but I feel like that should probably be fixed beforehand.

@SteveMacenski In ROS Noetic `geographic_info` should depend on the Python 3 equivalent `python3-catkin-pkg` instead. Further, if doesn't need the CLI tools then it should depend on `python-catkin-pkg-modules` in Melodic and earlier, and `python3-catkin-pkg-modules` in Noetic.

**Comment by SteveMacenski** [comment]
Ah ok. I'm not a python user in general so I'll probably need someone to sanity check it for me that everything's been properly updated. I did a glance over it and the obvious things I'm aware of from 2.7-3.4 look to be done already.

If that's the case, I can update that stuff and ship it out

**Comment by clalancette** [comment]
@sloretz Should we close this out now that Noetic has been released?

**Comment by clalancette** [comment]
I'm going to go ahead and close this now that Noetic is released.  Feel free to reopen if needed, or open up follow-up tasks.
