### ISSUE TITLE
Python 3 compatibility

### ISSUE THREAD

**Issue by dirk-thomas** [ros/rosdistro#2427]
Getting ROS _core_ (up to _ros_tutorials_) to build:
- [x] ros-infrastructure/catkin_pkg#72 ~~0.1.23~~
- [x] ros-infrastructure/catkin_pkg#80 0.1.24 released as _python3-catkin-pkg_
- [x] _python3-empy_ package is available now
- [x] ros-infrastructure/rosdep#279 0.10.24 released as _python3-rosdep_
- [x] ros-infrastructure/rosdistro#32 0.2.17 released as _python3-rosdistro_
- [x] ros-infrastructure/rosinstall_generator#12 0.1.5 released as _python3-rosinstall-generator_
- [x] ros-infrastructure/rospkg#48 1.0.26 released as _python3-rospkg_
- [x] ros/catkin#544, ros/catkin#571, ros/catkin#645, ros/catkin#646
- [x] ros/genmsg#35, ros/genmsg#37
- [x] ros/gencpp#11
- [x] ros/genpy#22
- [x] ros/common_msgs#18
- [x] ros/ros#41
- [x] ros/rospack#25, ros/rospack#27, ros/rospack#29
- [x] ros/ros_tutorials#13

**Comment by dirk-thomas** [comment]
I will close this ticket since there is no specific work on this item. In the meantime a couple of platforms are using Python 3 by default and over time patches have been contributed to various parts of ROS. If further work is necessary please just create tickets / pull requests against the specific ROS package.
