### ISSUE TITLE
[meta] OS X support in indigo

### ISSUE THREAD

**Issue by NikolausDemmel** [ros/rosdistro#4597]
This is a meta issue to track all the issues around OS X support in `indigo` (see #4663 for `hydro` issues).

For now the following issues need to be fixed for `desktop_full` to build from source on OS X:
- [x] [`10.9` only] `orocos_kdl` needs to be re-released and the depending patches in `robot_state_publisher` and `robot_model` need to be merged & released (https://github.com/orocos/orocos_kinematics_dynamics/pull/4#issuecomment-44429121). _Update:_ `orocos_kdl` was released to indigo and hydro, so we are waiting on the merge and release of https://github.com/ros/robot_model/pull/43 and https://github.com/ros/robot_state_publisher/pull/5. _Update 2:_ all patches have been released 
- [x] `rqt_robot_plugins` needs to be re-released with recently merged patches (https://github.com/ros-visualization/rqt_robot_plugins/pull/65, https://github.com/ros-visualization/rqt_robot_plugins/pull/66)
- [x] rodep installing `gcc` needs to be addressed: https://github.com/ros-infrastructure/rosdep/issues/328 
- [x] theora_image_transport sometimes fails to compile, restarting the compilation usually fixes it. Some missing dependencies are the problem: https://github.com/ros-perception/image_transport_plugins/pull/13
- [x] cmake and brewed python do not work together well. An experimental alternative LibPython cmake module can be installed by `brew remove cmake; brew install nikolausdemmel/devel/cmake`. See https://github.com/Homebrew/homebrew/issues/25118.
- [x] using system python leads to issues when formulae with dependecies on python are installed, because by default the bottles are installed and bottle depend on brewed python (and therefore install them). See https://github.com/Homebrew/homebrew/issues/31229.
- [x] `qt_gui` and dependent packages fail to run because of outdated PyQt on Homebrew. See https://github.com/ros-visualization/qt_gui_core/issues/47 and https://github.com/Homebrew/homebrew/pull/30881. _Update:_ PyQt 4.11.1 formula has been released in homebrew.
- [ ] `rviz` does not run with ogre 1.7 and crashes with 1.9: https://github.com/ros-visualization/rviz/issues/782

_The following is a collection of workarounds on top of the [install instructions](http://wiki.ros.org/hydro/Installation/OSX/Homebrew/Source) needed to address the above issues (applies to `desktop_full` builds):_

---

_Currently no workarounds_

---

_These are install instructions put together by @mikepurvis_:

https://gist.github.com/mikepurvis/9837958

Read carefully and understand what is going on rather than just blindly copy/pasting commands. These instructions deal with the cmake FindPythonLibs issue by specifying the lib/include path when compiling (rather than using the patched cmake formula) and installs the hydro version of rviz.

_@pgorczak has modified @mikepurvis's install instructions to use system python instead of brewed python_:

https://gist.github.com/pgorczak/66f99462bf251afbd2bc

**Comment by davetcoleman** [comment]
I'm not sure where the best place to report this is, or where to ask for help. On a completely new install of Yosemite (hard drive wipe) just now I had to do the following for Indigo:

I had to manually install pydot with the ``-H`` flag:

> sudo -H pip install -U pydot

After rosdep install completed, I still had to run

> pip install empy

> brew install poco

**Current Issues**

I get this warning message when running catkin_isolated:

> CMake Warning at cmake/test/nosetests.cmake:97 (message):
  nosetests not found, Python tests can not be run (try installing package
  'python-nose')
Call Stack (most recent call first):
  cmake/all.cmake:146 (include)
  CMakeLists.txt:8 (include)

But I cannot resolve that dependency:

> pip install python-nose
Collecting python-nose
  Could not find any downloads that satisfy the requirement python-nose
  No distributions at all found for python-nose

**Comment by wjwwood** [comment]
@davetcoleman please don't use the quote mechanism to put in code snippets or console output. I've updated your comment.

> I'm not sure where the best place to report this is, or where to ask for help.

I would have recommended starting on answers.ros.org, because some of these things may not be bugs.

> I had to manually install `pydot` with the `-H` flag:
> ...

The `sudo -H` problem as been addressed and is in the latest version of `rosdep`, which is `0.11.1`:

https://github.com/ros-infrastructure/rosdep/pull/369

For some reason I don't get that version when I install `rosdep` myself, though it is listed as the latest version on pypi:

https://pypi.python.org/pypi/rosdep

@tfoote is looking into it.

> After rosdep install completed, I still had to run:
> ...

If `rosdep` ran successfully you should not have had to do all of that. That's the purpose of the `rosdep install ...` step from the instructions. I would need to know what exact steps you took to know why it didn't work for you. Simply stating something didn't happen isn't enough information to help. Please consider what you're asking before you post to ensure that you've included enough information for someone to help you.

> But I cannot resolve that [`python-nose`] dependency:
> ...

@davetcoleman, really? It just has a different name in `pip`. One small investigation into the problem, e.g. `pip search nose` or `rosdep resolve python-nose` or Google'ing "install python-nose on os x", would have revealed the problem. And anyways most users wouldn't have run into the problem normally since `rosdep` should have installed it for them before they tried to build anything.

> I also get this warning many times:
> ...

This is because Hoembrew installs a really new version of CMake. I haven't had time to make an issue about it nor have I had time to investigate it. However, as far as I can tell it doesn't affect your ability to build the packages on OS X.

> Rviz does not build with error (similar to ros-visualization/rviz#782):
> ...

The original post is already tracking this I think:

> rviz does not run with ogre 1.7 and crashes with 1.9: ros-visualization/rviz#782

**Comment by wjwwood** [comment]
> For some reason I don't get that version when I install rosdep myself, though it is listed as the latest version on pypi:
> 
> https://pypi.python.org/pypi/rosdep
> 
> @tfoote is looking into it.

This has already been resolved, running `sudo -H pip install -U rosdep` should get you the latest version.

**Comment by wjwwood** [comment]
Also, for others who come later:

> I had to manually install `pydot` with the `-H` flag:

Passing `-H` to `sudo` is not required to install `pydot`, it's just that the latest version of `pip` warns if you do not use `-H` because it cannot store logs correctly. `pydot` should have been installed regardless.

**Comment by davetcoleman** [comment]
Sorry, my explanations were brief because I have a clean install of Yosemite (wiped hard drive) and so the background info is pretty simple. Everything is the latest. I ran rosdep and it did not report any errors. I was trying to help by providing some simple feedback - I could also just not report my fixes and keep them to myself.

Also, I did Google something to the effect of "install python-nose on os x" and I did run other methods for install nose. I can't remember why they didn't work and I'm not at the Mac at the moment.

**Comment by wjwwood** [comment]
> I could also just not report my fixes and keep them to myself.

@davetcoleman I'm sorry if you feel I've offended you in some way, that was not my intention, but if you're serious about that comment then I don't think keeping to yourself helps anyone.

I'm not sure what you want me to say. Neither of your follow up comments give anything more to go on. All I can do is push you for more information, like:

- What commands did you run?
- Did you have all of your sources you wanted to build checked out before running `rosdep`?
- Where did you run `rosdep`, was it in the same folder as the `src` folder which contained the packages' source code?
- Can you go back and run `rosdep` again but with the `-s` option and post the result?
- What did you try when installing `python-nose` on OS X? Why didn't work?

I'd like to help you and improve the workflow for others but without answers to questions like these I can't.

I know you're smart and capable, I just wish you would take the time required to formulate better feedback. Because the reality is that if you don't do it, then you're forcing me to make a decision to either ignore the feedback or risk a large amount of my own time trying to reproduce something you've reported based on vague feedback. And I, just like you and everyone else, have lots of things to do and not enough time to do them.

If you're displeased with me for asking you to do give better feedback, I won't apologize for that, because I know you're capable of it. An ounce of thoughtful feedback is worth a mountain of unsubstantiated feedback.

**Comment by davetcoleman** [comment]
I'm afraid we've had some miscommunications - I didn't mean to hijack this thread or get into an argument and again I apologize. I should have prefaced my issues with "These are just some notes I jotted down why reading through a bunch of different Github issues, ROS answers, and many Google Searches."  I don't develop on Mac - I'm just trying to help a lab mate whose software is Mac-only that needs to communicate with mine. I don't understand pip, or python dependencies. I was hoping like others before me in this thread I could weight in on my current experience following the all the provided resources I could find. 

When I made the silly remark "I could also just not report my fixes and keep them to myself." it was because I was a little offended when you corrected me 3 times in my original post. In my mind I was just trying to help, this isn't high priority to me, and I know this current Github issue is posted as "meta" and not the best place for tons of details. I'd be happy to open separate issues for the things I mentioned, I just couldn't figure out where to do so, as I explained in the first sentence of my issue. I understand that you were doing your best to address my issues, and your help so far has been thorough.

I haven't been back on my Mac yet so have no extra details to provide.

**Comment by pgorczak** [comment]
Just adding another data point here. I built indigo successfully on Yosemite using system Python and hydro rviz. I forked @mikepurvis installation notes to document [my build process](https://gist.github.com/pgorczak/66f99462bf251afbd2bc) (tl;dr I wrote a shell script that installs brew dependencies against system Python and I had to patch rviz headers that get processed by the Qt MOC).

**Comment by crazyorc** [comment]
The latest robot_model (1.11.7) has an unresolved dependency on 'pcre-dev' (was pcrecpp).  I've added a mapping for that key into osx-homebrew and created a pull request for it.

**Comment by tfoote** [comment]
In light of the qt4 qt5 hard transition on osx are we still expecting qt based things to work on osx from indigo? http://wiki.ros.org/indigo/Installation/OSX/Homebrew/Source if not we can probably close this ticket.

**Comment by mikepurvis** [comment]
Indigo is dead to me on OS X— Homebrew isn't supporting QT4, so it's basically a non-starter.

Lunar + QT5 works fine though: https://github.com/mikepurvis/ros-install-osx

**Comment by tfoote** [comment]
Ok, since the remaining todo on this is rviz on indigo for osx, I'm going to close this.
