### ISSUE TITLE
[meta] OS X support in hydro

### ISSUE THREAD

**Issue by NikolausDemmel** [ros/rosdistro#4663]
This is a meta issue to track all the long-standing issues around OS X support in `hydro` (see #4597 for `indigo` issues) and provide a reference for needed workarounds.

The following issues need to be fixed for `desktop_full` to build from source on OS X:

- [x] [`10.9` only] `orocos_kdl` needs to be re-released and the depending patches in `robot_state_publisher` and `robot_model` need to be merged & released (https://github.com/orocos/orocos_kinematics_dynamics/pull/4#issuecomment-44429121). *Update:* `orocos_kdl` was released to indigo and hydro, so we are waiting on the merge and release of https://github.com/ros/robot_model/pull/43 and https://github.com/ros/robot_state_publisher/pull/5. *Update2:* only the `robot_model` release is still missing (it is released to indigo already). *Update3:* all patches have been released.
- [x] [`10.9` only] CUDA needs to be disabled in `opencv2`, see ros-gbp/opencv2-release#4
- [x] rodep installing `gcc` needs to be addressed: https://github.com/ros-infrastructure/rosdep/issues/328 
- [x] some python/cmake related issues: https://github.com/ros-visualization/qt_gui_core/pull/46, https://github.com/ros-visualization/rviz/pull/788
- [x] https://github.com/ros-visualization/python_qt_binding/pull/12 needs to be backportet and released to hydro.
- [ ] cmake and brewed python do not work together well. An experimental alternative LibPython cmake module can be installed by `brew remove cmake; brew install nikolausdemmel/devel/cmake`. See https://github.com/Homebrew/homebrew/issues/25118.
- [ ] using system python leads to issues when formulae with dependecies on python are installed, because by default the bottles are installed and bottle depend on brewed python (and therefore install them). See https://github.com/Homebrew/homebrew/issues/31229.

*The following is a collection of workarounds on top of the [install instructions](http://wiki.ros.org/hydro/Installation/OSX/Homebrew/Source) needed to address the above issues (applies to `desktop_full` builds):*

---

**Comment by grafoteka** [comment]
Hi! i'm trying to catkin_make all the packages and i'm having the next error:
CMake Warning at /Users/jdeleon/indigo_desktop_full_ws/install_isolated/share/catkin/cmake/test/gtest.cmake:66 (message):
  skipping gtest 'image_geometry-utest' in project 'image_geometry'
Call Stack (most recent call first):
  /Users/jdeleon/indigo_desktop_full_ws/install_isolated/share/catkin/cmake/test/gtest.cmake:34 (catkin_add_executable_with_gtest)
  test/CMakeLists.txt:3 (catkin_add_gtest)


CMake Error at test/CMakeLists.txt:4 (target_link_libraries):
  Cannot specify link libraries for target "image_geometry-utest" which is
  not built by this project.

Do you know how to install that library?

Thank you

**Comment by wjwwood** [comment]
@grafoteka Please ask this on answers.ros.org, since this issue is not the appropriate place to ask this question. And when you do so, include more information, like what tutorial you are following or what you're trying to do and what command you are running exactly. For example, your files are in `install_isolated` but you say you're using `catkin_make` and not `catkin_make_isolated`, which doesn't seem to be right.

**Comment by wjwwood** [comment]
Since Hydro is EOL I'm going to close this in favor of the Jade meta issue.
