### ISSUE TITLE
Fedora Package Support

### ISSUE THREAD

**Issue by cottsay** [ros/rosdistro#4918]
This is a tracking ticket for rolling out support for packaging ROS on Fedora Linux using RPMs.

This issue will be modified and updated as the plan progresses and tasks are accomplished. It should also be used for general discussion on the subject.

The general plan is to leverage as much of the existing infrastructure as possible to keep maintainability as straightforward as possible.
### Tasks for RPM creation
- [x] 1a. Finish RPM generation in `bloom` (https://github.com/ros-infrastructure/bloom/pull/282)
  
  > This PR will bring the RPM generator to a functional state and will enable RPM generation by default on all new track configurations. It will not modify existing packages at all.
- [x] 1b. Target Fedora versions in `rosdistro` (https://github.com/ros/rosdistro/pull/4919)
  
  > Without defining which versions of Fedora are targeted on which ROS distros, `bloom` will not perform any RPM generation despite the aforementioned PR. Both of these must happen for RPM generation to happen _in the wild_, but each can be merged before the other without consequence.
- [x] ~~1c. Enable generation in existing packages~~
  
  > ~~This should be done after the `bloom` patch is merged. The configuration for a track is created from a default template when the track is created, so we need to add the `rosrpm` command to the command list for existing track configurations.~~
  > ~~This simply entails a PR against the package's `master` branch in the release repository. After that, initial generation should be performed, but is not necessary, as the workaround repositories [1] will continue to work until the official release repository has RPM branches present. An example of such a pull request can be seen at (https://github.com/smd-ros-release/pololu_smc_driver-release/pull/1).~~
  > `bloom` will prompt the user to update the 'action' list so that maintainers can update it then. A great feature!
### Tasks for RPM building

The South Dakota School of Mines & Technology (SDSM&T) has offered to build the RPM packages that are generated by bloom for consumption by the community. A Jenkins buildfarm has been created [2] and is currently operational. In order for continued and uninterrupted support, some things need to happen:
- [x] 2a. Merge RPM buildfarm code into main repository
  
  > The current RPM buildfarm code [3] was forked from the main buildfarm long ago. It was designed in such a way that it can easily coexist in the same codebase, as this eases in maintainability.
- [x] 2b. Develop a method for synchronization between staging repositories
  
  > Right now, the `shadow-fixed` repository is sync'd with `building` by means of a call to `rsync`. While this works for `building`=>`shadow-fixed` transitions, a better method should be employed for sync's from `shadow-fixed`=>`stable`. It would also be a good idea to leverage delta RPMs for updates to reduce the download size of updates. These _drpms_ would be created during this stage. It should also be decided where the `public` packages should reside (on ROS servers?). It is clear that the `building` repository and probably the `shadow-fixed` should stay on-campus with a Gig-E link to the build slaves.

The vast majority of ROS packages will require no code updates what-so-ever to be packaged into RPMs. A few weeks ago, I had packaged over 96% of ROS Hydro [4] and 99% of ROS Indigo [5] successfully using this system as a proof-of-concept.

I hope that the community will see this as a stepping stone to more support on more distributions, especially ones in the RedHat family (CentOS and RHEL).

If you are interested in helping in this effort, or have comments, suggestions or concerns, please speak up!

[1] http://github.com/smd-ros-rpm-release/
[2] http://csc.mcs.sdsmt.edu/jenkins/
[3] http://github.com/cottsay/buildfarm/
[4] http://csc.mcs.sdsmt.edu/ros/rpmbuild/hydro.html
[5] http://csc.mcs.sdsmt.edu/ros/rpmbuild/indigo.html

**Comment by DarthSpock** [comment]
I see it's been awhile since this one's been updated. Looking to move to Fedora soon and was wondering if this work has been completed. Also, anything that works in Fedora will work in RHEL by default (RHEL inherits all it's code from Fedora). Also for awareness, creating a snap: `snap install ros-indigo` as an example would be the better way for supporting other distros including Fedora.

**Comment by timn** [comment]
Are you aware of the [ROS copr](https://copr.fedorainfracloud.org/coprs/thofmann/ros/) and the [generator script](https://pagure.io/ros) used? @morxa, maybe you want to chime in here?

**Comment by morxa** [comment]
Thanks @timn for pointing this out, I was not aware that there was a (somewhat) ongoing discussion here!

So I've been working on ROS for Fedora for a while. The current state is as follows:
* [`rosfed`](https://pagure.io/ros/blob/master/f/rosfed.py) is a SPEC file generator that generates a SPEC file for a ROS package. It uses the `rosinstall_generator` to fetch dependencies, it generates a SPEC file that includes all BuildRequires and Requires, and it can build and update recursively. As an example, `rosfed.py -r --changelog "Update to latest release" desktop_full` would generate all SPEC files that are necessary to install `desktop_full`. There is some tooling in place to add patches, and add and replace dependencies that are specific for Fedora.
* There is an integration with Fedora's COPR, so it is possible to build packages directly from `rosfed` in a COPR. This will automatically figure out a build order that builds dependencies first. This allows to build a full stack with one command.
* Those tools were used to package a number of stacks (`desktop_full`, `move_base`, `moveit`). All those packages are available at the [ROS COPR](https://copr.fedorainfracloud.org/coprs/thofmann/ros/). Currently, this only contains kinetic packages, but the generator can use any ROS distribution (it may require additional patches and dependecy changes).
* All ROS packages are installed in `/usr/lib64/ros`. I chose to not put libs directly into `/usr/lib64`, mainly because the concept of SONAMEs is almost non-existent in ROS land. Fedora prohibits libraries without proper SONAMEs in the linker path.
* I've been working on customized requires/provides filter, so as an example `tf2` would provide `ros(libtf2.so()(64bit))` (instead of `libtf2.so()(64bit)`), to clearly separate system libraries from ROS libraries. This is still work in progress.
* The ultimate goal is to get those packages into Fedora proper. But this will be a big effort and will require help. I have not started organizing anything into that direction, as I wanted to figure out the technical details first. Also, from a practical point of view, the ROS COPR serves its purpose, so the pressure to get these packages into Fedora is not very high.
* Fedora modularity may actually be huge benefit for ROS, as it would decouple the ROS distro from the Fedora distro, e.g., you could choose which ROS distro you want to have.

Any feedback/testers/improvements are very welcome!

**Comment by tfoote** [comment]
@timn Thanks for the connection
@morxa We've already been generating spec files using bloom automatically every time we make a release. For example a recent geometry2 release here: https://github.com/ros-gbp/geometry2-release/blob/rpm/ros-melodic-tf2-geometry-msgs-0.6.1-0_28/rpm/ros-melodic-tf2-geometry-msgs.spec

It would be great to merge your work with that generator already. From @cottsay 's past work it' has fully worked to generate rpms for a distro. Right now it's defaulting to using our standard distribution target of /usr but that's not required. And with some cleanup it would hopefully be able to get pretty close to the requirments needed for submitting packages upstream to Fedora automatically.

Also separating out the spec file generator could potentially be integrated into https://github.com/ros-infrastructure/superflore which is a tool for batch operations on distros.  It's currently used for gentoo and there is an OpenEmbedded work coming for it. Adding the generation of a full rosdistro into a COPR would be relatively feasible.

**Comment by lukehutch** [comment]
@morxa Thanks for providing COPR packages for ROS.

I am trying to install your COPR ROS packages on Fedora 30. The Fedora 30 and rawhide repos does not have all the packages that the Fedora 29 repo contains, and additionally the files in the Fedora 30 and rawhide repos were actually built for Fedora 27 (they have "fc27" in the name). The Fedora 29 repo depends on an old version of boost that is not available on Fedora 30.

I'm trying to build the packages from source, but running into issues. Is there any chance you could please update your COPR repo for Fedora 30, and ideally also update to the newest release of ROS (if it doesn't require much in the way of new patches etc.)?

Thank you!

**Comment by tfoote** [comment]
We've landed RHEL 8 support. Congrats @cottsay for the long running persistence!

**Comment by WSLUser** [comment]
CentOS 7 and Fedora support are more likely be desired than RHEL 8 but it's a good start. Thanks for putting some work into this. Please add to EPEL for CentOS 7 and ensure COPR is fully updated.

**Comment by cottsay** [comment]
Here's the tracking ticket for bringing RPM support for the buildfarm: ros-infrastructure/ros_buildfarm#736
There was no tracking ticket for the deployment side of things, but you can get an idea of that work by [browsing the related PRs](https://github.com/ros-infrastructure/cookbook-ros-buildfarm/pulls?q=is%3Apr+is%3Aclosed+pulp).

> Please add to EPEL for CentOS 7

This work was funded by a party interested in RHEL 8 specifically, though the infrastructure could be used for RHEL 7 or Fedora as well (I believe we'll need some updates to Bloom because of [breaking changes in f33](https://fedoraproject.org/wiki/Changes/CMake_to_do_out-of-source_builds)). We need to gauge how much of a burden carrying additional RPM distributions would be before we could make any decisions about building for more distros on [build.ros2.org](https://build.ros2.org). I'm confident that a significant portion of ROS 2 will build successfully on RHEL 7 using devtoolset-8, but there are big challenges surrounding extremely old versions OpenCV and many Python packages - challenges we face far fewer of on RHEL 8. Hopefully delivering RHEL 8 RPMs for Galactic will give us a better idea of the maintenance impact.

Note that these packages are built in the same way that EPEL packages are, and are therefore usable on RHEL or any RHEL clone - not just CentOS.

>  ensure COPR is fully updated

This solution builds RPM packages on [build.ros2.org](https://build.ros2.org) in the same system as the official Ubuntu packages are built. It does not use COPR or any other external build services, and leverages the same release automation as the Ubuntu builds use. Package maintainers don't need to do anything extra to get RPM builds, and the released packages should always be in-sync with the Ubuntu packages.

The COPR mentioned by @morxa above is an unrelated effort, and appears to target ROS 1. Right now, we have no plans to build RPM packages on [build.ros.org](https://build.ros.org) for Fedora or RHEL.

Fedora has always been challenging to align with the ROS buildfarm model because the releases are relatively short-lived, and retroactively targeting a newer platform after a ROS distribution has already shipped isn't supported by Bloom. That isn't a problem for RHEL because of the slow release cadence - it makes for a stable target for us to refine the RPM build process against. This doesn't mean we'll never build Fedora packages using the ROS buildfarm, it just means that it's a little more challenging.

I use Fedora for my primary ROS development workstation. I've been working to [build ROS RPM packages](https://github.com/smd-ros-rpm-release) for [the better part of a decade](https://github.com/cottsay/buildfarm). I'd love to see the ROS buildfarm churn out Fedora packages :smile: RHEL is just an easier target right now.

**Comment by lukehutch** [comment]
Has there been any surveying effort to determine which of the RPM-based distributions is most worth supporting? My assumption would be that the sort of people who tinker with ROS are far more likely to be using Fedora than RHEL or Centos.

I have been using thofmann's copr for ROS on Fedora, and he has been doing a lot of great work to keep it up to date with Fedora releases, including updating the distro for all the big Python changes (between F31 and F32, IIRC), and a range of big API/ABI version changes in various libraries. I'm using ROS without any issues on F33 with this repo, but it looks like he has a version for F34 already. Has any of his work been reused for the RHEL port? If not, is there a way to combine these efforts?

https://copr.fedorainfracloud.org/coprs/thofmann/ros/

**Comment by morxa** [comment]
> 
> > ensure COPR is fully updated
> 
> This solution builds RPM packages on [build.ros2.org](https://build.ros2.org) in the same system as the official Ubuntu packages are built. It does not use COPR or any other external build services, and leverages the same release automation as the Ubuntu builds use. Package maintainers don't need to do anything extra to get RPM builds, and the released packages should always be in-sync with the Ubuntu packages.

I think that's one of the big differences between your approach and mine. I have a Fedora background and therefore my goal was to build ROS packages with Fedora tools rather than ROS tools. Your background is ROS, so you're using ROS tools. Both approaches make sense in their way :) But this would also be a major challenge when trying to combine those.

> 
> The COPR mentioned by @morxa above is an unrelated effort, and appears to target ROS 1. Right now, we have no plans to build RPM packages on [build.ros.org](https://build.ros.org) for Fedora or RHEL.

Yes, mainly because we have not decided to make the switch to ROS2 yet. We could definitely give it a try if there is interest.

> 
> I use Fedora for my primary ROS development workstation. I've been working to [build ROS RPM packages](https://github.com/smd-ros-rpm-release) for [the better part of a decade](https://github.com/cottsay/buildfarm). I'd love to see the ROS buildfarm churn out Fedora packages smile RHEL is just an easier target right now.

Out of curiosity, have you tried the ROS COPR?

**Comment by cottsay** [comment]
> Out of curiosity, have you tried the ROS COPR?

I haven't! The next time I need to work on ROS 1 packages, I'll give it a shot.
