### ISSUE TITLE
Jade Kick-off Checklist

### ISSUE THREAD

**Issue by wjwwood** [ros/rosdistro#6435]
This is a checklist of things to do for the Jade kick-off (pre development and development) based on our internal todo document:

- [x] Choose distribution name: Jade
- [x] Add to REP3 with proposed platforms and minimum requirements @wjwwood https://github.com/ros-infrastructure/rep/pull/89
- [x] List on ROS wiki with expected release date (http://wiki.ros.org/Distributions)
- [x] EOL distribution N-3 (Groovy)
- [x] Add to reprepro-updater list and run script to populate @tfoote U+V supported https://github.com/ros-infrastructure/reprepro-updater/commit/b239e98cb6acc34e878f337d6be624faf0f5a1f3

----

- [x] Import third party packages
 - ~~@tfoote can you compile a list of third party libraries we currently have for Indigo?~~ List of previous imports below. Pulled from here: https://github.com/ros-infrastructure/reprepro-updater/tree/master/config not all apply forward. Some are upstream now. 
 - [X] ~~bullet Use upstream version~~
 - [x] catkin_lint @roehling
 - [x] ceres
 - [x] colladadom (not currently built in PPA newer than Trusty 20140106 https://launchpad.net/~openrave/+archive/ubuntu/testing )
 - [X] ~~empy (comment from dirk-thomas: this shouldn't be necessary anymore as of Utopic?)~~
 - [x] gazebo5 ~~gazebo2/gazebo~~ 
    - [x] trusty
    - [x] utopic
    - [x] vivid
 - [x] pcl (https://github.com/ros-infrastructure/rep/pull/89#issuecomment-66874811)
 - [x] openni2 (see pcl link)
 - [X] ~~qtsixa Not needed. Functionality integrated in kernel 3.15 and newer~~
 - [x] ~~urdfdom (upsstream in trusty and newer)~~

----

- [x] Add newly supported Ubuntu platforms to list of platforms for each Python package (in `stdeb.cfg`)
 - [x] bloom @wjwwood 0.5.15 (new release)
 - [x] catkin_pkg @dirk-thomas 0.2.6 (no new release)
 - [x] catkin_tools @wjwwood (no new release)
 - [x] ~~jenkins_tools @tfoote~~
 - [x] rosdep @wjwwood 0.11.0 (new release)
 - [x] rosdistro @dirk-thomas 0.4.0 (new release)
 - [x] rosinstall @wjwwood 0.7.4 (new release)
 - [x] rosinstall_generator @wjwwood 0.1.10 (new release)
 - [x] rospkg @dirk-thomas 1.0.32 (new release)
 - [x] vcstool @dirk-thomas 0.1.7 (no new release)
 - [x] vcstools @wjwwood 0.1.36 (new release)
 - [x] wstool @wjwwood 0.1.5 (new release)

----

- [x] Create distribution files in ros/rosdistro @dirk-thomas: #6436
 - [x] @cottsay Can you look at the ros/rosdistro distribution file for Jade and make sure to get a Fedora target in there? For now we dropped it because we didn't know which it should be targeted to.
- [x] Create doc folders on OSU ftp servers (`api`, `changelog`, `tags`) @dirk-thomas: http://docs.ros.org/jade/
- [x] Remove jobs from build farm for EOL'ed distribution (Groovy)
 - [x] @dirk-thomas actually remove them
- [x] Create build farm views for Jade @dirk-thomas
- [x] Create static jobs in ros-infrastructure/buildfarm and deploy to Jenkins @dirk-thomas: ros-infrastructure/buildfarm@1bb58dcd3f71452fcd21d68c7c2811e5d1d0ee70
 - [x] Ensure rosdistro cache is being generated and uploaded @dirk-thomas: http://www.ros.org/rosdistro/
 - [x] Ensure debbuild status page is being generated and posted @dirk-thomas: http://www.ros.org/debbuild/

----

- [x] Remove EOL'ed distro from pre-release website @dirk-thomas: https://github.com/ros-infrastructure/prerelease_website/commit/ec8b8f80255191d55e0f500718e6aea17a18e425 since we don't support groovy releases anymore anyway there is no reason to keep the prerelease website
- [x] Add documentation to the wiki (maybe in the bloom tutorials) for doing a pre-release locally using the new build farm tools: https://github.com/ros-infrastructure/ros_buildfarm/blob/master/doc/jobs/prerelease_jobs.rst
- [x] Link to new pre-release documentation from the old pre-release website: http://prerelease.ros.org/select_distro

----

- [x] Add Jade button to the wiki @wjwwood
- [x] Update version macro in wiki @wjwwood
- [x] Add standard distribution wiki pages (planning, migration, etc...) @wjwwood
- [x] Add distribution to ROS browse tabs @wjwwood
- [x] Edit wiki pages to contain proper content for the Jade tag.
 - [x] catkin: http://wiki.ros.org/action/diff/catkin?action=diff&rev1=158&rev2=159
 - [x] Tracked separately on this issue: https://github.com/ros/rosdistro/issues/6878

----

- [x] Release `ros-base` packages into Jade
 - [x] catkin @dirk-thomas
 - [x] genmsg @dirk-thomas
 - [x] gencpp @dirk-thomas
 - [x] genlisp @dirk-thomas
 - [x] genpy @dirk-thomas
 - [x] roscpp_core @dirk-thomas
 - [x] message_generation @dirk-thomas
 - [x] message_runtime @dirk-thomas
 - [x] rosbag_migration_rule @dirk-thomas
 - [x] std_msgs @dirk-thomas
 - [x] ros_comm_msgs @dirk-thomas
 - [x] cmake_modules @wjwwood
 - [x] rospack @dirk-thomas
 - [x] ros @dirk-thomas
 - [x] roslisp @dirk-thomas
 - [x] ros_comm @dirk-thomas
 - [x] rosconsole_bridge @dirk-thomas
 - [x] common_msgs @tfoote
 - [x] ros_tutorials @dirk-thomas
 - [x] actionlib @esteve
 - [x] angles @tfoote
 - [x] bond_core @esteve
 - [x] dynamic_reconfigure @esteve
 - [x] class_loader @esteve
 - [x] pluginlib @esteve
 - [x] nodelet_core @esteve
 - [x] common_tutorials @wjwwood
 - [x] ~~metapackages @dirk-thomas~~ This is part of the Beta, I would count this as the alpha ticket (basically `ros-base`).

----

- [x] Announce availability of the Jade build farm @wjwwood (ETA: Jan 1st, 2015)
- [x] Update mirror documentation @tfoote 
- [x] Announce and kick-off logo design @tfoote

**Comment by tfoote** [comment]
geometry and geometry_experimental are almost ready. I've pinged @smits about orocos_kdl which is the only blocker geometry_experimental and python_orocos_kdl is needed in addition for geometry.

**Comment by vrabaud** [comment]
hey guys, could we finally set tf to deprecated in Indigo and remove it from jade ?

**Comment by mikeferguson** [comment]
> hey guys, could we finally set tf to deprecated in Indigo and remove it from jade ?

That sounds like a ton of work -- there are 210 packages in Indigo that still depend on TF. Technically tf has been deprecated since hydro -- however it seems that docs/tutorials are still not updated (see https://github.com/ros/geometry_experimental/issues/20 and https://github.com/ros/geometry_experimental/issues/21)

**Comment by dirk-thomas** [comment]
The script to run prerelease tasks locally is finished in the new buildfarm repository (see description of the task https://github.com/ros-infrastructure/ros_buildfarm/blob/master/doc/jobs/prerelease_jobs.rst). This needs to be documented in the wiki for users to know how to call it.

**Comment by wjwwood** [comment]
@dirk-thomas I added two todo's in the OP related to documentation for using the local prerelease tool.

I read over the doc you linked too, but there are few things I noticed:

- It only describes `generate_prerelease_script.py` but there seems to also be a `generate_prerelease_overlay_script.py`
- It says that it generates a shell script, but then later describes all of the python scripts which can be called manually. I'm not sure which is correct, but it is a little confusing to read.

This document doesn't stand very well on it's own because it references terms from other documents and generally assumes some implicit understanding of terminology and the system around it. The user documentation on the wiki will need to be more layman.

Also are there plans to release these scripts as a Python package with versioning and all that?

**Comment by dirk-thomas** [comment]
The documentation in the repository is only meant for developers running their own farm to understand what the jobs do and how they work. I don't plan to include user documentation in there. The wiki on the other hand should have a description suitable for endusers telling them how to run a prerelease task.

For the buildfarm itself I don't plan to release the package but keep using the repository checkout. For the user using the prerelease script we can decide either or as long as the wiki page describes it.

**Comment by wjwwood** [comment]
> The documentation in the repository is only meant for developers running their own farm to understand what the jobs do and how they work.

Ok, I was just pointing out some odd things I noticed about that particular document.

> I don't plan to include user documentation in there. The wiki on the other hand should have a description suitable for endusers telling them how to run a prerelease task.

I agree, I don't think the user documentation should go in the repository. I think I said the same thing.

> For the buildfarm itself I don't plan to release the package but keep using the repository checkout.

That's fine by me, but out of curiosity why do you want to do that? I see the advantage while you are actively developing on it, but otherwise why wouldn't we release it as a Python package?

> For the user using the prerelease script we can decide either or as long as the wiki page describes it.

So you would propose splitting the pre-release stuff out and releasing it for users? I think the user experience would be better and simpler if they could just install something from `apt-get` or even `pip` (think OS X with `boot2docker`).

**Comment by dirk-thomas** [comment]
Cloning the `ros_buildfarm` repository works on a clean slave. If the repository is released as a Python package it needs to be installed / updated on the slaves which gets us away from working on a machine without any prerequisites.

For the user we can still release a Python package which is installable via apt and/or pip. That should be unrelated to the way we use it on the buildfarm.

**Comment by wjwwood** [comment]
> Cloning the `ros_buildfarm` repository works on a clean slave. If the repository is released as a Python package it needs to be installed / updated on the slaves which gets us away from working on a machine without any prerequisites.

I see, you don't want to have to add our apt-get repositories before using the slave. I think it would still be good to make it a Python package, then you could install it from source using `pip`'s VCS support:

https://pip.pypa.io/en/latest/reference/pip_install.html#vcs-support

You can install it from a release tag, a branch, or a specific commit using that.

If you use that in conjunction with a virtualenv then you can get it installed without needing to manually clone and add it to the `PATH` and `PYTHONPATH` and all that stuff.

> For the user we can still release a Python package which is installable via apt and/or pip. That should be unrelated to the way we use it on the buildfarm.

So... that sounds like we should make the `ros_buildfarm` repo a Python package and not split out the prerelease scripts into a different package? I'm fine with either, but we should decide on something and do it, because I really can't document the process until we know what the user has to do to get the right software.

I guess the pre-release isn't super vital on the first round of releases, since the overlay will always be empty. However, I would still like to address it sooner than later.

**Comment by smits** [comment]
I apparently missed some ping. Is it just about releasing kdl into jade or
are there other issues?

R.

On Thu, Jan 1, 2015 at 3:25 AM, Tully Foote <notifications@github.com>
wrote:

> geometry and geometry_experimental are almost ready. I've pinged @smits
> <https://github.com/smits> about orocos_kdl which is the only blocker
> geometry_experimental and python_orocos_kdl is needed in addition for
> geometry.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ros/rosdistro/issues/6435#issuecomment-68478780>.
>



-- 
Ruben Smits, Roboticist - Founder
+32 479 511 786
Intermodalics - Kapeldreef 60, 3001 Heverlee - BELGIUM
www.intermodalics.eu

**Comment by wjwwood** [comment]
@vrabaud, I agree with @mikeferguson that seems like a quite large action item. I think it would be a good idea to spend some time improving the state of the `tf2` docs and maybe even actively encouraging people to convert to `tf2` in order to decrease the number of people still using `tf`, but completely removing it seems pretty intractable at this point.

**Comment by wjwwood** [comment]
> Should we also aim to release geometry, rviz, rqt as soon as possible?

I guess you mean because we need them to release the `metapackages` package?

**Comment by tfoote** [comment]
@smits it's just for you to release kdl into jade. There are no expected issues.

**Comment by dirk-thomas** [comment]
@wjwwood The problem with creating a Debian package of `ros_buildfarm` will be that its dependencies (e.g. `python3-rosdistro`) will collide with the Python 2 packages the users will have installed.

**Comment by wjwwood** [comment]
@dirk-thomas That's ok, I'll look at what needs to be done to packetize the repo and make a pull request.

**Comment by smits** [comment]
Ok,

I'll try to squeeze it in this week.

R.

On Tue, Jan 6, 2015 at 12:14 AM, Tully Foote <notifications@github.com>
wrote:

> @smits <https://github.com/smits> it's just for you to release kdl into
> jade. There are no expected issues.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ros/rosdistro/issues/6435#issuecomment-68799551>.
>



-- 
Ruben Smits, Roboticist - Founder
+32 479 511 786
Intermodalics - Kapeldreef 60, 3001 Heverlee - BELGIUM
www.intermodalics.eu

**Comment by tfoote** [comment]
catkin_lint and ceres imported: f508a3c9af6512707c9f2ad7da79f284cbb1f67d

**Comment by tfoote** [comment]
@falkTX Would it be possible to turn on builds of qtsixa for utopic and vivid in your PPA? https://launchpad.net/%7Efalk-t-j/+archive/ubuntu/qtsixa

**Comment by wjwwood** [comment]
@tfoote it looks like @falkTX added Utopic and Vivid to his PPA: https://launchpad.net/~falk-t-j/+archive/ubuntu/qtsixa

@falkTX is there any reason we should wait before pulling those in?

**Comment by falkTX** [comment]
I'm out of the loop here, but if you're using utopic/vivid the kernel has full support for sixaxis now.
There's no reason for qtsixa to exist anymore since ~3.15 kernel. Just plug the sixaxis in and you get the full leds + rumble working.
afaik BlueZ 5 will have native support for sixaxis and DualShock4 controllers, without the need to patch it.

qtsixa is a dead, unneeded project right now.
I have no interest in maintaing it.

**Comment by tfoote** [comment]
@falkTX That's great to hear thanks for the update. We're just going through all the old dependencies and making sure they're available. In this case we will remove it from the list to import.

**Comment by tfoote** [comment]
Gazebo imports: https://github.com/ros-infrastructure/reprepro-updater/commit/3c333ac5c6b2fedada768e60582eaa2c437079ae I had to disable vivid since they don't exist. 

And https://github.com/ros-infrastructure/buildfarm_deployment_config/commit/c09e7ac4cda9987dd74335360c21a35cfab0ba4b

**Comment by tfoote** [comment]
I've checked off gazebo. I have not imported it for vivid, but it's targeted for upstream in vivid.

**Comment by tfoote** [comment]
Gazebo5 vivid is now imported too. We can remove the import rule when it's accepted upstream.

**Comment by wjwwood** [comment]
@tfoote can you check on the items still open:

- Update mirror documentation @tfoote
- openni2 (see pcl link)

Close them if they're done, or update on them if they cannot be acted on yet.

**Comment by tfoote** [comment]
mirror docs/formula updated: https://github.com/ros-infrastructure/mirror/commit/5c3bb7e24e186a68d2f5c6ed018b8af85be6d58f https://github.com/ros-infrastructure/mirror/commit/53d3a4420d9c462075564f2f7b28cd854c6a0f64

**Comment by wjwwood** [comment]
Finally rolled out the prerelease stuff, closing this :checkered_flag:

**Comment by dirk-thomas** [comment]
The updated instructions for prereleases (http://wiki.ros.org/regression_tests#How_do_I_setup_my_system_to_run_a_prerelease.3F) do not consider that users have ROS and therefore the Python 2 versions of all the tools installed. Therefore installing the Python 3 tools via apt-get is not an option.

This question has been raise on http://answers.ros.org/question/210233/docker-prerelease-setting-and-ros-indigo-incompatible/

**Comment by wjwwood** [comment]
Yeah, someone asked me about that by email, but I haven't had time to find a solution yet. I guess I installed the Python 2 version and then the Python 3, ran it and then installed catkin for the first time after it ran.

**Comment by wjwwood** [comment]
@dirk-thomas The prerelease website was updated by Tom Moore, and I just verified that his change worked on a fresh VM. So the instructions should be good to go.
