### ISSUE TITLE
Jade: Release Check List

### ISSUE THREAD

**Issue by wjwwood** [ros/rosdistro#8008]
This ticket is used to collect things that need to be done for the upcoming Jade release.

Existing Task Sets:

- [x] Jade kickoff list #6435
- [x] Jade documentation audit #6878
- [x] Jade community documentation audit #8284

Documentation:

- Update verbiage on these wiki pages, e.g. 'upcoming release' vs. 'current release':
 - [x] http://wiki.ros.org/jade/Installation
 - [x] http://wiki.ros.org/jade
- Check the state of links:
 - [x] http://wiki.ros.org/jade/Installation/UbuntuARM (http://www.ros.org/debbuild/armhf/jade.html)

- [x] Turtlesim icon @wjwwood

- [x] k-turtle name @esteve 

- [x] rosbuild tickets @gerkey is on it https://github.com/ros/rospack/pull/48

- [x] indigo-jade debbuild comparison page @dirk-thomas 

- [x] remove groovy from header doc links (https://github.com/ros-infrastructure/roswiki/pull/133)

Checklist from internal Google Drive doc:

ROS Wiki

- [x] make distroN the default distro
  - https://github.com/ros-infrastructure/roswiki/blob/master/custom/js/rosversion.js#L40 (https://github.com/ros-infrastructure/roswiki/commit/cea8bc5b704ba54a0ab0421b58909249ccfbbc5a)
- [x] Version macro for distroN needs to be updated from “Expected in distroN” to “distroN” (https://github.com/ros-infrastructure/roswiki/commit/44b62e47d188487952ccd65775bac24305500eec)
- [x] Update symlink for default API doc:
  - /home/rosbot/docs/api → /home/rosbot/docs/distroN/api
- [x] Update http://wiki.ros.org/Distributions
- [x] Update http://wiki.ros.org/ROS/Installation to point to distroN

ROS browse

- [x] update default distro:
 - https://github.com/ros-infrastructure/rosbrowse/commit/55dbea7565ccad7159f531de3ed9cd2ed4ec540e

Communication

- [x] Announcement email pointing to migration guide
 - Post to ros-users
 - Post to blog
 - Post to G+
 - Post to Twitter

www.ros.org

- [x] Update www.ros.org bottom row widget to point to new release with logo
- [x] Update www.ros.org/install to point to new release with logo

**Comment by dirk-thomas** [comment]
Referencing #6435 and #6878.

**Comment by dirk-thomas** [comment]
* [x] update REP 142 to move tutorials to desktop metapackage: ros-infrastructure/rep#100
* [ ] update REP 142 to include geneus for Jade
* [ ] release metapackages

**Comment by wjwwood** [comment]
@dirk-thomas @tfoote @esteve I'm going to start working on these. I might delegate some tasks. Let me know if you don't have time to do it.

**Comment by wjwwood** [comment]
@dirk-thomas can you tell me how to do the "Update symlink for default API doc" item or do it for me?

**Comment by esteve** [comment]
K-turtle will be named Kinetic Kame.

**Comment by wjwwood** [comment]
@esteve it's supposed to be a secret :stuck_out_tongue:.

**Comment by tfoote** [comment]
@wjwwood I created a visualization of the Jade development cycle up to today: https://www.youtube.com/watch?v=-Bpaz94krAo  We've had 40 committers and over 500 packages.

**Comment by wjwwood** [comment]
Thanks, I'll include that in my draft email (I'll send it around to you guys tonight and send it tomorrow).

**Comment by dirk-thomas** [comment]
@wjwwood  `api` is imply a symbolic link to `indigo/api`. I updated it.

**Comment by wjwwood** [comment]
> @wjwwood api is simply a symbolic link to indigo/api. I updated it.

I wasn't sure which server it was on, thanks.

**Comment by wjwwood** [comment]
How do I do the www.ros.org updates?

**Comment by dirk-thomas** [comment]
I would suggest to put both releases on the install page (http://www.ros.org/install/):
* Indigo (LTS)
* Jade (latest release)

**Comment by wjwwood** [comment]
I agree, I've been sort of showcasing them both in each place I can.

**Comment by wjwwood** [comment]
I still need to know how to update www.ros.org, has someone done that before? Is that on the internal wiki (I can't seem to access it from here)?

**Comment by tfoote** [comment]
@wjwwood I emailed you pointers to the credentials

**Comment by wjwwood** [comment]
@tfoote I didn't get an email like that, did you send it to my work account?

**Comment by tfoote** [comment]
Yeah, I've resent it with the subject "ros.org credentials"

**Comment by wjwwood** [comment]
Ok, I got the www.ros.org updates.
