### ISSUE TITLE
Kinetic Kick-off Checklist

### ISSUE THREAD

**Issue by esteve** [ros/rosdistro#9945]
This is a checklist of things to do for the Kinetic kick-off (pre development and development):

- [x] Choose distribution name: Kinetic
- [x] commission a logo @tfoote
- [x] Add to REP3 with proposed platforms and minimum requirements @esteve https://github.com/ros-infrastructure/rep/pull/106
- [x] List on ROS wiki with expected release date (http://wiki.ros.org/Distributions)
- [x] EOL distribution N-3 (Hydro)
- [x] Add W+X to bootstrap repository on repos.ros.org  @tfoote W+X supported https://github.com/ros-infrastructure/reprepro-updater/commit/951812014a2f9afef53ffd90fa06a41af3fd8b4f
- [x] Add W+X to buildfarm_deployment_config @tfoote https://github.com/ros-infrastructure/buildfarm_deployment_config/commit/9817752851a4123294342ec0af3a134376940d0c (note that one is not the live one it's for reference only)
- [x] Add W+X to ros_buildfarm/common.py ros-infrastructure/ros_buildfarm#223

----

- [x] Import third party packages
  - [x] `colladadom` (@wjwwood pinged Rosen on Feb. 29th)

----

- [x] Add newly supported Ubuntu platforms to list of platforms for each Python package (in `stdeb.cfg`), in order of dependency (for ROS-L, do this as soon as debs for new Ubuntu are available, in pre-alpha!):
  - [x] rospkg (uploaded, no need to rerelease): ros-infrastructure/rospkg#96
  - [x] catkin_pkg (uploaded, no need to rerelease): ros-infrastructure/catkin_pkg#135
  - [x] rosdistro (uploaded, no need to rerelease): https://github.com/ros-infrastructure/rosdistro/pull/61
  - [x] rosdep (uploaded, no need to rerelease): ros-infrastructure/rosdep#434
  - [x] vcstools (uploaded, no need to rerelease): https://github.com/vcstools/vcstools/pull/111
  - [x] wstool (uploaded, no need to rerelease): https://github.com/vcstools/wstool/pull/84
  - [x] rosinstall (uploaded, no need to rerelease): https://github.com/vcstools/rosinstall/pull/101
  - [x] bloom (uploaded, no need to rerelease): ros-infrastructure/bloom#379
  - [x] rosinstall_generator (uploaded, no need to rerelease): ros-infrastructure/rosinstall_generator#32
  - [x] catkin_tools (uploaded, no need to rerelease): https://github.com/catkin/catkin_tools/pull/289
  - [x] vcstool: https://github.com/dirk-thomas/vcstool/commit/cbf78fed3ae846fb0b4ba97c860fed1523821b0b
- [x] Use [`ros_release_python`](https://github.com/ros-infrastructure/ros_release_python) to make the currently released versions available in the new distros. Use the `--includedeb` option

----

- [x] create Docker images for the new platforms for all targets: `i386`, `armhf`
  - [x] @tfoote to do this for Wily

----

- [x] Create distribution files in ros/rosdistro https://github.com/ros/rosdistro/pull/10443
- [x] add [ros_buildfarm_config](https://github.com/ros-infrastructure/ros_buildfarm_config) kinetic entries https://github.com/ros-infrastructure/ros_buildfarm_config/pull/25
  - [x] create new mailing list (https://groups.google.com/forum/#!forum/ros-buildfarm-kinetic) with exactly the same settings as the existing ones
- [x] Disable jobs from build farm for EOL'ed distribution (Hydro)
- [x] generate new management jobs (see https://github.com/ros-infrastructure/ros_buildfarm/blob/master/doc/deploy_configuration.rst)

----

- [x] Remove old pre-release website link from pre-release website @jacquelinekay
- [x] Add new column in prerelease website for the new distro with theme and placeholder image @jacquelinekay https://github.com/ros-infrastructure/prerelease_website/pull/24
  - [x] Test prerelease process

----

- [x] Add Kinetic button to the wiki @jacquelinekay 
  - ros-infrastructure/roswiki#156
- [x] Add distribution to ROS browse tabs @jacquelinekay
- [ ] Edit wiki pages to contain proper content for the Kinetic tag. @jacquelinekay
- [x] Add standard distribution wiki pages (planning, migration, etc...) @jacquelinekay
  - [x] http://wiki.ros.org/kinetic
  - [x] http://wiki.ros.org/kinetic/Planning
  - [x] http://wiki.ros.org/kinetic/Migration Stubbed out, need to fill in content (e.g. qt migration)
  - [x] http://wiki.ros.org/kinetic/Planning/Maintenance
    -  Page made, update periodically with metapackage_status.py as packages get released
  - [x] http://wiki.ros.org/kinetic/Installation
    - only filling out Ubuntu and Ubuntu armhf right now, we can fill in other experimental platforms later

----

- [x] Release `ros-base` packages into Kinetic
 - [x] catkin @dirk-thomas
 - [x] genmsg @dirk-thomas
 - [x] gencpp @dirk-thomas
 - [x] geneus @k-okada https://github.com/ros/rosdistro/pull/10726
 - [x] genlisp @dirk-thomas
 - [x] genpy @dirk-thomas
 - [x] roscpp_core @dirk-thomas
 - [x] message_generation @dirk-thomas
 - [x] message_runtime @dirk-thomas
 - [x] rosbag_migration_rule @dirk-thomas
 - [x] std_msgs @dirk-thomas
 - [x] ros_comm_msgs @dirk-thomas
 - [x] cmake_modules @wjwwood
 - [x] rospack @dirk-thomas
 - [x] ros @dirk-thomas
 - [x] roslisp @dirk-thomas
 - [x] ros_comm @dirk-thomas
 - [x] rosconsole_bridge @dirk-thomas
 - [x] common_msgs @tfoote
 - [x] ros_tutorials @dirk-thomas ~~(waiting for turtlesim icon, conversion to Qt5)~~
 - [x] actionlib @wjwwood and @mikaelarguedas
 - [x] angles @tfoote
 - [x] bond_core @wjwwood and @mikaelarguedas
 - [x] dynamic_reconfigure @wjwwood and @mikaelarguedas 
 - [x] class_loader @wjwwood and @mikaelarguedas 
 - [x] pluginlib @wjwwood and @mikaelarguedas 
 - [x] nodelet_core @wjwwood and @mikaelarguedas 
 - [x] common_tutorials @wjwwood

----

- [x] Announce availability of the Kinetic build farm @jacquelinekay
- [ ] Update mirror documentation (see https://github.com/ros-infrastructure/mirror/commits/master for examples)
- [x] Announce logo design and kick off t-shirt campaign @tfoote

**Comment by mikepurvis** [comment]
In advance of the full Kinetic debs being ready, it's unfortunate that the independent packages like python-rosdep, python-rosinstall-generator, etc are not available for Wily and Xenial, so that users can get ahead of the game with testing Indigo and Jade packages on the newer versions of system deps.

**Comment by esteve** [comment]
bloom: https://github.com/ros-infrastructure/bloom/pull/379
catkin_pkg: https://github.com/ros-infrastructure/catkin_pkg/pull/135
python-rosdep: https://github.com/ros-infrastructure/rosdep/pull/434
rosinstall_generator: https://github.com/ros-infrastructure/rosinstall_generator/pull/32
rospkg: https://github.com/ros-infrastructure/rospkg/pull/96

@mikepurvis sorry for the delay. Is there any other package that needs to be updated? Thanks.

**Comment by dirk-thomas** [comment]
@esteve Please look at the checklist from the previous releases for additional Python packages: e.g. #6435.

**Comment by dirk-thomas** [comment]
I have released: `catkin`, `genmsg`, `gencpp`, `genlisp`, `genpy`, `roscpp_core`, `message_runtime`, `rosbag_migration_rule`, and `rospack`. Currently I need to wait for a `geneus` before I can proceed.

**Comment by jacquelinekay** [comment]
@k-okada, any chance you could make a Kinetic release of `geneus` so that we can proceed with Kinetic core package releases? Many thanks.

**Comment by jacquelinekay** [comment]
my bad, I wasn't watching rosdistro and just noticed that Kei has already released geneus...

**Comment by k-okada** [comment]
as for Collada, we put deb for wily at
https://launchpad.net/~openrave/+archive/ubuntu/release/+sourcepub/6188757/+listing-archive-extra
https://launchpad.net/~openrave/+archive/ubuntu/release/+sourcepub/6188756/+listing-archive-extra

it seems collada becomes default ubuntu package from xenial, so I think
we'll use default(ubuntu) version of collada for xenial and launch pad
version (from ros repository) for wily, it seems tricky, but better than
install two version of collada.
http://packages.ubuntu.com/xenial/libcollada-dom2.4-dp-dev

--
◉ Kei Okada

**Comment by wjwwood** [comment]
I contacted Rosen about updating the openrave ppa, but if you guys already did it then I'll open a or later tonight to add it to our import rules.

**Comment by k-okada** [comment]
I haven't talked to Rosen directly, but pretty sure that he's super busy
 and updated the deb for him.
Did you have any response from Rosen? If not, please go ahead.

--
◉ Kei Okada

**Comment by wjwwood** [comment]
No nothing yet. I'll set it up.

**Comment by dirk-thomas** [comment]
I have released: `message_generation`, `std_msgs`, `ros_comm_msgs`, `ros`, `roslisp`, `ros_comm`, `rosconsole_bridge`, and `common_msgs`.

In order to release `ros_tutorials` we need the Kinetic `turtlesim` icon and I will convert `turtlesim` to Qt5. But that should not block the release of most other downstream packages.

**Comment by dirk-thomas** [comment]
I have released: message_generation, std_msgs, ros_comm_msgs, ros, roslisp, ros_comm, rosconsole_bridge, and common_msgs.

In order to release ros_tutorials we need the Kinetic turtlesim icon and I will convert turtlesim to Qt5. But that should not block the release of most other downstream packages.

Update: I have created a kinetic-devel branch for ros_tutorials which uses Qt5.
